# Generated by Django 6.1.1 on 2026-09-22 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cooperative', models.TextField()),
                ('price_rwf', models.IntegerField(help_text='Whole Rwandan francs. Isoko does not handle fractional RWF.', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
