name: Ruff Formatting

on: 
  pull_request:
    branches: ["main"]
  push:
    branches: ["dev"]
  workflow_dispatch: 

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        
      - name: Setup Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: 3.12
        
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Ruff Linting
        run: ruff check .

  build:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        
      - name: Setup Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: 3.12
        
      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v4.4.1
        

      # - name: printing a name
      #   run: |
      #     name = ${{secrets.MY_NAME}}
      #     print(name)
